### ISSUE TITLE
\r not recognized in eval. Seemingly quits eval.

### ISSUE THREAD

**Issue by lufinkey** [ChaiScript/ChaiScript#142] opened 2014-10-31 19:22 UTC
I noticed that the \r character seems to cause a problem when you call chai.eval on a string with \r characters in it. (haven't tested with \r\n. Just \r) I didn't get an error, however. It just abandoned the eval and didn't add any symbols from it. Problem "temporarily" solved by replacing all \r characters with \n, but that's a quick, not optimal, fix.

**Comment by lufinkey** [comment] 2015-05-04 19:50
Oh um I'm not sure where that file is now. All I remember is that it had an
issue when the newline was only \r, and not \r\n or \n

**Comment by lufinkey** [comment] 2015-05-04 19:50
I can look for it when I get the chance

**Comment by lefticus** [comment] 2015-05-04 19:55
OK, I just looked it up and the only systems that ever considered that a legitimate line ending was the Commodore 8bit systems, and I'm unable to reproduce the issue. Re-open it if you come across it again.

**Comment by lefticus** [comment] 2015-05-04 20:05
I just noticed that:

```
eval> eval("print(1)\r");
terminate called after throwing an instance of 'chaiscript::Boxed_Value'
```

So that's something for me to try and figure out. That probably shouldn't be an unhandled exception.

**Comment by lefticus** [comment] 2015-08-11 21:01
I believe these errors have been fixed now with the last set of parser fixes that were committed on develop.

**Closed by lefticus** 2015-08-11 21:01 UTC
