### ISSUE TITLE
Changed behaviour in v6 overriding +=

### ISSUE THREAD

**Issue by PooperPig** [ChaiScript/ChaiScript#340] opened 2017-04-05 11:52 UTC
Xcode (C++ 14)
Mac Os Sierra
64 Bit
 

```
var a = Vec2(12.0,3.0);
var b = Vec2(13.0,4.0);

var c = a + b;
print("\n c is " + to_string(c.x));

a += b;
print("\n a is " + to_string(a.x));

```
**Expected output**

> c is 25
> a is 25

**Actual output**

> c is 3.43421e-39 
> a is 25

```

auto module = std::make_shared<chaiscript::Module>();
        // add the math library so we can use math stuff in our script
        auto mathlib = chaiscript::extras::math::bootstrap();
        
        // Add the Vec2 type so we can use them and return them in scripts
        module->add(chaiscript::user_type<cocos2d::Vec2>(), "Vec2");
        module->add(chaiscript::constructor<cocos2d::Vec2(float, float)>(), "Vec2");            // Define the Vec2 Constructor
        module->add(chaiscript::fun(&cocos2d::Vec2::x),"x");                                    // Define the Vec2 'properties'
        module->add(chaiscript::fun(&cocos2d::Vec2::y),"y");
        module->add(chaiscript::constructor<cocos2d::Vec2(cocos2d::Vec2)>(),"Vec2");
        module->add(chaiscript::fun(&Vec2::operator=), "=");
        module->add(chaiscript::fun(&Vec2::operator+), "+");
        module->add(chaiscript::fun(&Vec2::operator+=), "+=");


```

the cocos2d:Vec2 is a simple vector of floats - see http://www.cocos2d-x.org/reference/native-cpp/V3.1rc0/d9/d7f/class_vec2.html for more info if it's relevant.

**Comment by lefticus** [comment] 2017-04-05 14:44
So to be clear, `+=` is working as expected, but `+` seems to have broken somehow?

**Comment by PooperPig** [comment] 2017-04-05 21:37
Yes, exactly.

**Comment by lefticus** [comment] 2017-04-16 18:58
Is it possible for you to make a complete standalone example that illustrates the problem please? If `+` is broken like this then we would have much more systemic issues in ChaiScript so there must be some other interaction that I'm not seeing.

**Comment by PooperPig** [comment] 2017-04-17 12:10
Ok - the attached project is an Xcode command-line project that demonstrates the issue.

If you run it using the 6.0.0 chai script, the output is

Script hi
4
2.764e+19
Program ended with exit code: 0

With the 5.8.1.version, the output is
Script hi
4
7
Program ended with exit code: 0ode: 0

The code is commented where I change it between the two versions.

I copied math.h into the chai script folder to make it simpler - and I am using the same math.h in both…

In Xcode I just change the header search path to point to one or the other chai script folder, and change the code as commented in ChaiscriptCreator.cpp

Let me know if there’s anything else I can do - I don’t generally have access to a Windows machine to try this on (and indeed wouldn’t know how to!)

Cheers

Max

**Comment by lefticus** [comment] 2017-05-04 14:11
GitHub didn't actually make the attachment when you sent it via email.

**Comment by PooperPig** [comment] 2017-05-05 02:46
[chaitest.zip](https://github.com/ChaiScript/ChaiScript/files/977997/chaitest.zip)
Hopefully that's uploaded now.

**Comment by lefticus** [comment] 2017-05-30 13:51
The issue is with your `+` overload, you have defined it as:

```cpp
inline const Vec2 Vec2::operator+(const Vec2& v) const
```

Declaring your return value as `const` is unnecessary and un-idiomatic (if there is such a word)

better to define it as:

```cpp
inline Vec2 Vec2::operator+(const Vec2& v) const
```

Which fixes the issue with ChaiScript.

However, this means there is still some issue with ChaiScript that was introduced in 6.0 and is causing the the lifetime of the object to get messed up. I will look into that as well in the next few minutes.

**Comment by lefticus** [comment] 2017-05-30 14:43
Ok, it has been fixed in develop branch. But I did also verify that compilers should be warning on your `const` return value type. You should turn up the warning level on your project also `-Wall -Wextra` as an absolute minimum for clang.

**Closed by lefticus** 2017-05-30 14:43 UTC

**Comment by PooperPig** [comment] 2017-05-31 11:08
Thanks Lefticus! 
The offending code is in a C++ game library (so I take no blame!)
The library does have a lot of build warnings - so I suspect I am getting a warning for this, but it's getting swallowed in all the other warnings.
Cheers - & thanks for the library and your help.
