### ISSUE TITLE
GCC: G++ 7.1.1 Build Error

### ISSUE THREAD

**Issue by Royal-806** [ChaiScript/ChaiScript#349] opened 2017-06-02 21:01 UTC
Fedora 26, GCC 7.1.1 std=C++1z
In a pretty much clean build environment I get this error
```
c++  '-IWrath@sha' '-I.' '-I../src' '-I../src/include' '-fdiagnostics-color=always' '-pipe' '-D_FILE_OFFSET_BITS=64' '-Wall' '-Winvalid-pch' '-Wnon-virtual-dtor' '-std=c++1z' '-O0' '-g' '-fconcepts' '-fpermissive' '-fPIC' '-MMD' '-MQ' 'Wrath@sha/Engine_Wrath.cpp.o' '-MF' 'Wrath@sha/Engine_Wrath.cpp.o.d' -o 'Wrath@sha/Engine_Wrath.cpp.o' -c ../src/Engine/Wrath.cpp
In file included from ../src/include/chaiscript/dispatchkit/proxy_functions_detail.hpp:24:0,
                 from ../src/include/chaiscript/dispatchkit/proxy_functions.hpp:27,
                 from ../src/include/chaiscript/dispatchkit/proxy_constructors.hpp:14,
                 from ../src/include/chaiscript/dispatchkit/dispatchkit.hpp:34,
                 from ../src/include/chaiscript/chaiscript_basic.hpp:12,
                 from ../src/include/chaiscript/chaiscript.hpp:823,
                 from ../src/Engine/Scripting/ScriptingEnv.hpp:11,
                 from ../src/Engine/Wrath.hpp:3,
                 from ../src/Engine/Wrath.cpp:13:
../src/include/chaiscript/dispatchkit/callable_traits.hpp: In instantiation of ‘struct chaiscript::dispatch::detail::Callable_Traits<bool (*)(const chaiscript::Boxed_Value&, const chaiscript::Boxed_Value&) noexcept>’:
../src/include/chaiscript/language/../dispatchkit/register_function.hpp:45:72:   required from ‘chaiscript::Proxy_Function chaiscript::fun(const T&) [with T = bool (*)(const chaiscript::Boxed_Value&, const chaiscript::Boxed_Value&) noexcept; chaiscript::Proxy_Function = std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>]’
../src/include/chaiscript/dispatchkit/bootstrap.hpp:522:43:   required from here
../src/include/chaiscript/dispatchkit/callable_traits.hpp:99:56: error: ‘operator()’ is not a member of ‘bool (*)(const chaiscript::Boxed_Value&, const chaiscript::Boxed_Value&) noexcept’
           typedef typename Function_Signature<decltype(&T::operator())>::Signature Signature;
                                                        ^~
../src/include/chaiscript/dispatchkit/callable_traits.hpp:99:56: error: ‘operator()’ is not a member of ‘bool (*)(const chaiscript::Boxed_Value&, const chaiscript::Boxed_Value&) noexcept’
In file included from ../src/include/chaiscript/dispatchkit/bad_boxed_cast.hpp:18:0,
                 from ../src/include/chaiscript/dispatchkit/dispatchkit.hpp:28,
                 from ../src/include/chaiscript/chaiscript_basic.hpp:12,
                 from ../src/include/chaiscript/chaiscript.hpp:823,
                 from ../src/Engine/Scripting/ScriptingEnv.hpp:11,
                 from ../src/Engine/Wrath.hpp:3,
                 from ../src/Engine/Wrath.cpp:13:
../src/include/chaiscript/dispatchkit/type_info.hpp: In instantiation of ‘static constexpr chaiscript::Type_Info chaiscript::detail::Get_Type_Info<T>::get() [with T = bool() const noexcept]’:
../src/include/chaiscript/dispatchkit/type_info.hpp:238:41:   required from ‘static std::vector<chaiscript::Type_Info> chaiscript::dispatch::Attribute_Access<T, Class>::param_types() [with T = bool() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:718:44:   required from ‘chaiscript::dispatch::Attribute_Access<T, Class>::Attribute_Access(T Class::*) [with T = bool() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/chaiscript_defines.hpp:92:47:   required from ‘std::shared_ptr<_Tp> chaiscript::make_shared(Arg&& ...) [with B = chaiscript::dispatch::Proxy_Function_Base; D = chaiscript::dispatch::Attribute_Access<bool() const noexcept, chaiscript::Boxed_Value>; Arg = {bool (chaiscript::Boxed_Value::*&)() const noexcept}]’
../src/include/chaiscript/language/../dispatchkit/register_function.hpp:84:121:   required from ‘chaiscript::Proxy_Function chaiscript::fun(T Class::*) [with T = bool() const noexcept; Class = chaiscript::Boxed_Value; chaiscript::Proxy_Function = std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>]’
../src/include/chaiscript/dispatchkit/bootstrap.hpp:423:41:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:790:31:   in constexpr expansion of ‘chaiscript::user_type<bool() const noexcept>()’
../src/include/chaiscript/dispatchkit/type_info.hpp:145:15: error: typeid of qualified function type ‘bool() const noexcept’
               &typeid(T),
../src/include/chaiscript/dispatchkit/type_info.hpp:146:15: error: typeid of qualified function type ‘chaiscript::detail::Bare_Type<bool() const noexcept>::type {aka bool() const noexcept}’
               &typeid(typename Bare_Type<T>::type));
../src/include/chaiscript/dispatchkit/type_info.hpp: In instantiation of ‘static constexpr chaiscript::Type_Info chaiscript::detail::Get_Type_Info<T>::get() [with T = void() const noexcept]’:
../src/include/chaiscript/dispatchkit/type_info.hpp:238:41:   required from ‘static std::vector<chaiscript::Type_Info> chaiscript::dispatch::Attribute_Access<T, Class>::param_types() [with T = void() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:718:44:   required from ‘chaiscript::dispatch::Attribute_Access<T, Class>::Attribute_Access(T Class::*) [with T = void() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/chaiscript_defines.hpp:92:47:   required from ‘std::shared_ptr<_Tp> chaiscript::make_shared(Arg&& ...) [with B = chaiscript::dispatch::Proxy_Function_Base; D = chaiscript::dispatch::Attribute_Access<void() const noexcept, chaiscript::Boxed_Value>; Arg = {void (chaiscript::Boxed_Value::*&)() const noexcept}]’
../src/include/chaiscript/language/../dispatchkit/register_function.hpp:84:121:   required from ‘chaiscript::Proxy_Function chaiscript::fun(T Class::*) [with T = void() const noexcept; Class = chaiscript::Boxed_Value; chaiscript::Proxy_Function = std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>]’
../src/include/chaiscript/dispatchkit/bootstrap.hpp:429:51:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:790:31:   in constexpr expansion of ‘chaiscript::user_type<void() const noexcept>()’
../src/include/chaiscript/dispatchkit/type_info.hpp:145:15: error: typeid of qualified function type ‘void() const noexcept’
               &typeid(T),
../src/include/chaiscript/dispatchkit/type_info.hpp:146:15: error: typeid of qualified function type ‘chaiscript::detail::Bare_Type<void() const noexcept>::type {aka void() const noexcept}’
               &typeid(typename Bare_Type<T>::type));
../src/include/chaiscript/dispatchkit/type_info.hpp: In instantiation of ‘static constexpr chaiscript::Type_Info chaiscript::detail::Get_Type_Info<T>::get() [with T = bool(const chaiscript::Type_Info&) const noexcept]’:
../src/include/chaiscript/dispatchkit/type_info.hpp:238:41:   required from ‘static std::vector<chaiscript::Type_Info> chaiscript::dispatch::Attribute_Access<T, Class>::param_types() [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:718:44:   required from ‘chaiscript::dispatch::Attribute_Access<T, Class>::Attribute_Access(T Class::*) [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/chaiscript_defines.hpp:92:47:   required from ‘std::shared_ptr<_Tp> chaiscript::make_shared(Arg&& ...) [with B = chaiscript::dispatch::Proxy_Function_Base; D = chaiscript::dispatch::Attribute_Access<bool(const chaiscript::Type_Info&) const noexcept, chaiscript::Boxed_Value>; Arg = {bool (chaiscript::Boxed_Value::*&)(const chaiscript::Type_Info&) const noexcept}]’
../src/include/chaiscript/language/../dispatchkit/register_function.hpp:84:121:   required from ‘chaiscript::Proxy_Function chaiscript::fun(T Class::*) [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value; chaiscript::Proxy_Function = std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>]’
../src/include/chaiscript/dispatchkit/bootstrap.hpp:430:40:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:790:31:   in constexpr expansion of ‘chaiscript::user_type<bool(const chaiscript::Type_Info&) const noexcept>()’
../src/include/chaiscript/dispatchkit/type_info.hpp:145:15: error: typeid of qualified function type ‘bool(const chaiscript::Type_Info&) const noexcept’
               &typeid(T),
../src/include/chaiscript/dispatchkit/type_info.hpp:146:15: error: typeid of qualified function type ‘chaiscript::detail::Bare_Type<bool(const chaiscript::Type_Info&) const noexcept>::type {aka bool(const chaiscript::Type_Info&) const noexcept}’
               &typeid(typename Bare_Type<T>::type));
../src/include/chaiscript/dispatchkit/type_info.hpp: In instantiation of ‘static constexpr chaiscript::Type_Info chaiscript::detail::Get_Type_Info<T>::get() [with T = const chaiscript::Type_Info&() const noexcept]’:
../src/include/chaiscript/dispatchkit/type_info.hpp:238:41:   required from ‘static std::vector<chaiscript::Type_Info> chaiscript::dispatch::Attribute_Access<T, Class>::param_types() [with T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:718:44:   required from ‘chaiscript::dispatch::Attribute_Access<T, Class>::Attribute_Access(T Class::*) [with T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value]’
../src/include/chaiscript/chaiscript_defines.hpp:92:47:   required from ‘std::shared_ptr<_Tp> chaiscript::make_shared(Arg&& ...) [with B = chaiscript::dispatch::Proxy_Function_Base; D = chaiscript::dispatch::Attribute_Access<const chaiscript::Type_Info&() const noexcept, chaiscript::Boxed_Value>; Arg = {const chaiscript::Type_Info& (chaiscript::Boxed_Value::*&)() const noexcept}]’
../src/include/chaiscript/language/../dispatchkit/register_function.hpp:84:121:   required from ‘chaiscript::Proxy_Function chaiscript::fun(T Class::*) [with T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value; chaiscript::Proxy_Function = std::shared_ptr<chaiscript::dispatch::Proxy_Function_Base>]’
../src/include/chaiscript/dispatchkit/bootstrap.hpp:435:46:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:790:31:   in constexpr expansion of ‘chaiscript::user_type<const chaiscript::Type_Info&() const noexcept>()’
../src/include/chaiscript/dispatchkit/type_info.hpp:145:15: error: typeid of qualified function type ‘const chaiscript::Type_Info&() const noexcept’
               &typeid(T),
../src/include/chaiscript/dispatchkit/type_info.hpp:146:15: error: typeid of qualified function type ‘chaiscript::detail::Bare_Type<const chaiscript::Type_Info&() const noexcept>::type {aka const chaiscript::Type_Info&() const noexcept}’
               &typeid(typename Bare_Type<T>::type));
In file included from ../src/include/chaiscript/dispatchkit/proxy_constructors.hpp:14:0,
                 from ../src/include/chaiscript/dispatchkit/dispatchkit.hpp:34,
                 from ../src/include/chaiscript/chaiscript_basic.hpp:12,
                 from ../src/include/chaiscript/chaiscript.hpp:823,
                 from ../src/Engine/Scripting/ScriptingEnv.hpp:11,
                 from ../src/Engine/Wrath.hpp:3,
                 from ../src/Engine/Wrath.cpp:13:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = void() noexcept; T = void() noexcept; Class = std::vector<chaiscript::Boxed_Value>; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = void() noexcept; Class = std::vector<chaiscript::Boxed_Value>]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘void (std::vector<chaiscript::Boxed_Value>::)() noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = void() noexcept; T = void() noexcept; Class = std::vector<chaiscript::Boxed_Value>; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = void() noexcept; Class = std::vector<chaiscript::Boxed_Value>]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘void (std::vector<chaiscript::Boxed_Value>::)() noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = bool(const chaiscript::Type_Info&) const noexcept; T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Type_Info; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Type_Info]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘bool (chaiscript::Type_Info::)(const chaiscript::Type_Info&) const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = bool(const chaiscript::Type_Info&) const noexcept; T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Type_Info; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Type_Info]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘bool (chaiscript::Type_Info::)(const chaiscript::Type_Info&) const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = bool() const noexcept; T = bool() const noexcept; Class = chaiscript::Type_Info; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool() const noexcept; Class = chaiscript::Type_Info]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘bool (chaiscript::Type_Info::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = bool() const noexcept; T = bool() const noexcept; Class = chaiscript::Type_Info; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool() const noexcept; Class = chaiscript::Type_Info]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘bool (chaiscript::Type_Info::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = const chaiscript::Type_Info&() const noexcept; T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘const chaiscript::Type_Info& (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = const chaiscript::Type_Info&() const noexcept; T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = const chaiscript::Type_Info&() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘const chaiscript::Type_Info& (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = bool(const chaiscript::Type_Info&) const noexcept; T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘bool (chaiscript::Boxed_Value::)(const chaiscript::Type_Info&) const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = bool(const chaiscript::Type_Info&) const noexcept; T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool(const chaiscript::Type_Info&) const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘bool (chaiscript::Boxed_Value::)(const chaiscript::Type_Info&) const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = void() const noexcept; T = void() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = void() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘void (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = void() const noexcept; T = void() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = void() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘void (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(const Class*) const [with Type = bool() const noexcept; T = bool() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:754:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:783:126: error: invalid use of non-static member function of type ‘bool (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<typename std::add_const<Type>::type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
../src/include/chaiscript/dispatchkit/proxy_functions.hpp: In instantiation of ‘std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> chaiscript::dispatch::Attribute_Access<T, Class>::do_call_impl(Class*) const [with Type = bool() const noexcept; T = bool() const noexcept; Class = chaiscript::Boxed_Value; std::enable_if_t<(! std::is_pointer<_Ptr>::value), chaiscript::Boxed_Value> = chaiscript::Boxed_Value]’:
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:757:35:   required from ‘chaiscript::Boxed_Value chaiscript::dispatch::Attribute_Access<T, Class>::do_call(const std::vector<chaiscript::Boxed_Value>&, const chaiscript::Type_Conversions_State&) const [with T = bool() const noexcept; Class = chaiscript::Boxed_Value]’
../src/Engine/Scripting/ScriptingEnv.hpp:40:1:   required from here
../src/include/chaiscript/dispatchkit/proxy_functions.hpp:777:95: error: invalid use of non-static member function of type ‘bool (chaiscript::Boxed_Value::)() const noexcept’
           return detail::Handle_Return<typename std::add_lvalue_reference<Type>::type>::handle(o->*m_attr);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by lefticus** [comment] 2017-06-02 21:11
This is a duplicate of #348 due to changes in C++17's handling of `noexcept` function types. It's fixed in `develop` branch.

**Closed by lefticus** 2017-06-02 21:11 UTC
